// This file is generated by Slice Machine. Update with care!

import Image from './Image';
import TestSection from './TestSection';

export {
	Image,
	TestSection,
};

export const components = {
	image: Image,
	test_section: TestSection,
};
